version: '3'
services:
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    container_name: nodejs-api
    volumes:
       - ./src:/usr/src/app/src
